/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import Server.ScoreCalculator;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.lang.reflect.Array;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class GameGUI extends javax.swing.JFrame {

    int selectedRow = -1;
    int selectedColumn = -1;
    int category;
    int score;
    private Server.Dice[] dices = new Server.Dice[5];
    private ClientConnection connection;
    private int currentTurnIndex = 0; // kimin sırası
    private int myPlayerIndex = 0; // bu client'ın oyuncu numarası
    private int rollCount = 0;
    private DefaultTableModel scoreTableModel;
    private StringBuilder gameOverSummary = new StringBuilder();

    /**
     * Creates new form GameGUI
     */
    /**
     * GameGUI sınıfının yapıcı metodudur. GUI bileşenlerini başlatır, başlangıç
     * durumu ayarlarını yapar ve sunucu bağlantısını kurar.
     */
    public GameGUI() {
        initComponents(); // NetBeans GUI Builder tarafından otomatik oluşturulan bileşenleri başlatır.

        // Oyun başlangıcında zar atma ve skor gönderme butonlarını devre dışı bırak.
        // Bu butonlar, oyuncunun sırası geldiğinde 'updateTurn' metodu tarafından etkinleştirilecektir.
        rollButton.setEnabled(false);
        sendButton.setEnabled(false);

        // Zar görsellerini başlangıç değerleriyle günceller.
        // Bu, oyunun başında GUI'de görünen zarların varsayılan görsellerini ayarlar.
        updateLabel(1, dice1);
        updateLabel(2, dice2);
        updateLabel(3, dice3);
        updateLabel(4, dice4);
        updateLabel(5, dice5);

        // Skor tablosunun modelini alır. Bu model, tabloya veri eklemek ve güncellemek için kullanılır.
        scoreTableModel = (DefaultTableModel) scoreTable1.getModel();

        try {
            // Sunucuya bağlanmak için ClientConnection nesnesini oluşturur.
            // "ec2-16-171-175-101.eu-north-1.compute.amazonaws.com" sunucunun IP adresi veya hostname'idir. (AWS'dan alınmıştır. )
            // 12345 ise sunucunun dinlediği port numarasıdır. 'this' parametresi, GameGUI'nin bir dinleyici olarak
            // sunucudan gelen mesajları işleyebilmesi için ClientConnection'a referansını verir.
            connection = new ClientConnection("ec2-16-171-175-101.eu-north-1.compute.amazonaws.com", 12345, this);
        } catch (Exception e) {
            // Sunucuya bağlanılamazsa hata mesajı gösterir ve uygulamadan çıkar.
            JOptionPane.showMessageDialog(this, "Sunucuya bağlanılamadı!", "Hata", JOptionPane.ERROR_MESSAGE);
            System.exit(1); // Uygulamayı kapatır.
        }

        // Pencere kapatma olayını dinlemek için bir WindowListener ekler.
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Pencere kapatıldığında sunucuya "QUIT" mesajı gönderir.
                // Bu, sunucunun bağlantıyı düzgün bir şekilde kapatmasını sağlar.
                if (connection != null) {
                    connection.sendMessage("QUIT");
                }
                System.exit(0); // Uygulamayı güvenli bir şekilde kapatır.
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoreTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        dice2 = new javax.swing.JLabel();
        dice3 = new javax.swing.JLabel();
        dice4 = new javax.swing.JLabel();
        dice5 = new javax.swing.JLabel();
        d1 = new javax.swing.JToggleButton();
        d2 = new javax.swing.JToggleButton();
        d3 = new javax.swing.JToggleButton();
        d4 = new javax.swing.JToggleButton();
        d5 = new javax.swing.JToggleButton();
        rollButton = new javax.swing.JButton();
        sendButton = new javax.swing.JButton();
        dice1 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));

        scoreTable1.setBackground(new java.awt.Color(255, 255, 255));
        scoreTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scoreTable1.setForeground(new java.awt.Color(102, 0, 0));
        scoreTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Oyuncu 1", "Oyuncu 2"
            }
        ));
        scoreTable1.setColumnSelectionAllowed(true);
        scoreTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        scoreTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scoreTable1.setShowGrid(true);
        scoreTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scoreTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(scoreTable1);
        scoreTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("YAHTZEE");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel1.setOpaque(true);

        categoryTable.setBackground(new java.awt.Color(255, 255, 255));
        categoryTable.setForeground(new java.awt.Color(102, 0, 0));
        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Player Name"},
                {"Ones"},
                {"Twos"},
                {"Threes"},
                {"Fours"},
                {"Fives"},
                {"Sixes"},
                {"Three of a Kind"},
                {"Four of a Kind"},
                {"Small Straight"},
                {"Large Straight"},
                {"Full House"},
                {"Chance"},
                {"Yahtzee"},
                {"TOTAL SCORE"}
            },
            new String [] {
                "Kategoriler"
            }
        ));
        categoryTable.setToolTipText("");
        categoryTable.setShowGrid(true);
        jScrollPane2.setViewportView(categoryTable);

        dice2.setBackground(new java.awt.Color(0, 0, 0));
        dice2.setForeground(new java.awt.Color(255, 255, 255));
        dice2.setText("jLabel3");
        dice2.setOpaque(true);

        dice3.setBackground(new java.awt.Color(0, 0, 0));
        dice3.setText("jLabel4");
        dice3.setOpaque(true);

        dice4.setBackground(new java.awt.Color(0, 0, 0));
        dice4.setText("jLabel5");
        dice4.setOpaque(true);

        dice5.setBackground(new java.awt.Color(0, 0, 0));
        dice5.setText("jLabel6");
        dice5.setOpaque(true);

        d1.setBackground(new java.awt.Color(204, 204, 204));
        d1.setForeground(new java.awt.Color(0, 0, 0));
        d1.setText("...");
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });

        d2.setBackground(new java.awt.Color(204, 204, 204));
        d2.setForeground(new java.awt.Color(0, 0, 0));
        d2.setText("...");
        d2.setToolTipText("...");
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });

        d3.setBackground(new java.awt.Color(204, 204, 204));
        d3.setForeground(new java.awt.Color(0, 0, 0));
        d3.setText("...");
        d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3ActionPerformed(evt);
            }
        });

        d4.setBackground(new java.awt.Color(204, 204, 204));
        d4.setForeground(new java.awt.Color(0, 0, 0));
        d4.setText("...");
        d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ActionPerformed(evt);
            }
        });

        d5.setBackground(new java.awt.Color(204, 204, 204));
        d5.setForeground(new java.awt.Color(0, 0, 0));
        d5.setText("...");
        d5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d5ActionPerformed(evt);
            }
        });

        rollButton.setBackground(new java.awt.Color(204, 204, 204));
        rollButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rollButton.setForeground(new java.awt.Color(102, 0, 0));
        rollButton.setText("ZAR AT");
        rollButton.setPreferredSize(new java.awt.Dimension(104, 28));
        rollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollButtonActionPerformed(evt);
            }
        });

        sendButton.setBackground(new java.awt.Color(204, 204, 204));
        sendButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sendButton.setForeground(new java.awt.Color(102, 0, 0));
        sendButton.setText("GÖNDER");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        dice1.setBackground(new java.awt.Color(0, 0, 0));
        dice1.setForeground(new java.awt.Color(255, 255, 255));
        dice1.setText("jLabel2");
        dice1.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dice3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dice4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dice5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dice3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d3)
                    .addComponent(d4)
                    .addComponent(d5)
                    .addComponent(d2)
                    .addComponent(d1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton)
                    .addComponent(rollButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       /**
     * Bu istemcinin oyuncu indeksini ayarlar.
     *
     * @param index Bu istemcinin temsil ettiği oyuncunun sunucudan aldığı
     * indeks.
     */
    public void setMyPlayerIndex(int index) {
        myPlayerIndex = index;
        System.out.println("Bu istemcinin oyuncu indeksi: " + myPlayerIndex);
    }

    /**
     * İstemci-sunucu bağlantısını sağlayan ClientConnection nesnesini ayarlar.
     *
     * @param connection Sunucu ile iletişim kurmak için kullanılacak
     * ClientConnection nesnesi.
     */
    public void setConnection(ClientConnection connection) {
        this.connection = connection;
    }

    /**
     * Bu istemcinin oyuncu indeksini döndürür.
     *
     * @return Bu istemcinin oyuncu indeksi.
     */
    public int getMyPlayerIndex() {
        return myPlayerIndex;
    }

    /**
     * Belirli bir zar değerine karşılık gelen görseli bir JLabel üzerine yükler
     * ve gösterir. Görselin boyutu ayarlanır ve JLabel'ın metni temizlenir.
     *
     * @param value Görüntülenecek zar değeri (1-6 arası).
     * @param label Zar görselinin yükleneceği JLabel.
     */
    protected void updateLabel(int value, javax.swing.JLabel label) {
        ImageIcon icon = new ImageIcon("C:\\Users\\user\\OneDrive\\Belgeler\\NetBeansProjects\\NetworkProject\\src\\main\\java\\Zarlar\\dice" + value + ".jpg");
        Image fotograf = icon.getImage();
        Image newimg = fotograf.getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(newimg);
        label.setIcon(icon);
        label.setText(null); // JLabel'ın metnini temizle, sadece görsel görünsün.
    }

    /**
     * Zar görsellerini ve ilgili Dice nesnelerinin değerlerini günceller. Yeni
     * atılan zar değerlerini GUI'ye yansıtır.
     *
     * @param values Güncellenecek 5 zarın değerlerini içeren dizi.
     */
    public void updateDice(int[] values) {
        // Zar görsellerini içeren JLabel dizisi.
        JLabel[] diceLabels = {dice1, dice2, dice3, dice4, dice5};
        for (int i = 0; i < 5; i++) {
            // Eğer ilgili Dice nesnesi henüz oluşturulmadıysa oluştur.
            if (dices[i] == null) {
                dices[i] = new Server.Dice();
            }
            dices[i].setValue(values[i]); // Dice nesnesinin değerini güncelle.
            updateLabel(values[i], diceLabels[i]); // JLabel'ın görselini güncelle.
            diceLabels[i].setEnabled(true); // Zar görsellerini etkileşimli hale getir.
        }
    }

    /**
     * Oyun sırası değiştiğinde GUI'yi günceller. Zar atma sayacını sıfırlar,
     * butonların etkinliğini ayarlar ve oyuncuya sıra bilgisini gösterir.
     *
     * @param index Sırası gelen oyuncunun indeksi.
     */
    public void updateTurn(int index) {
        currentTurnIndex = index; // Mevcut sıra indeksini güncelle.
        rollCount = 0; // Zar atma sayacını sıfırla.
        boolean myTurn = (index == myPlayerIndex); // Sıranın bu istemcide olup olmadığını kontrol et.

        rollButton.setEnabled(myTurn); // Sadece kendi sırasıysa zar atma butonunu etkinleştir.
        sendButton.setEnabled(myTurn); // Sadece kendi sırasıysa skor gönderme butonunu etkinleştir.

        JToggleButton[] toggleButtons = {d1, d2, d3, d4, d5}; // Zar tutma butonları.
        JLabel[] diceLabels = {dice1, dice2, dice3, dice4, dice5}; // Zar görselleri.

        for (int i = 0; i < 5; i++) {
            toggleButtons[i].setSelected(false); // Tüm zar tutma butonlarının seçimini kaldır.
            diceLabels[i].setEnabled(true); // Tüm zar görsellerini etkinleştir.
        }

        // Oyuncuya sıra bilgisi veren bir mesaj kutusu göster.
        if (myTurn) {
            JOptionPane.showMessageDialog(this, "Sıra Sizde! Zar atmak için 'ZAR AT' butonuna basın.");
        } else {
            // Oyuncu indeksleri 0'dan başladığı için ekrana 1 ekleyerek gösteriyoruz.
            JOptionPane.showMessageDialog(this, "Sıradaki oyuncu: Oyuncu " + (currentTurnIndex + 1) + ". Lütfen bekleyin.");
        }
        // Seçili skor hücresini sıfırla.
        selectedRow = -1;
        selectedColumn = -1;
    }

    /**
     * Oyun sonu özetini oluşturmak için StringBuilder'ı başlatır. Bu metod,
     * yeni bir oyun sonu özeti toplanmaya başlandığında çağrılmalıdır.
     */
    public void showGameOverSummary() {
        gameOverSummary = new StringBuilder("Oyun Sonu Sonuçları:\n"); // Özetin başlangıç metnini ayarla.
        // Bu metod çağrıldığında, eski mesajlar temizlenir veya yeni bir özet penceresi için hazırlanılır.
    }

    /**
     * GUI'yi yeni bir oyun için sıfırlar. Zar görsellerini, butonları ve skor
     * tablosunu başlangıç durumuna getirir.
     */
    public void resetGUIForNewGameRequest() {
        // GUI güncellemelerini Swing'in olay gönderim iş parçacığında güvenli bir şekilde çalıştır.
        SwingUtilities.invokeLater(() -> {
            // Zar görsellerini varsayılan hale getir (örneğin 1'den 5'e kadar zarlar).
            updateLabel(1, dice1);
            updateLabel(2, dice2);
            updateLabel(3, dice3);
            updateLabel(4, dice4);
            updateLabel(5, dice5);

            // Tüm zar tutma butonlarının seçimini kaldır.
            d1.setSelected(false);
            d2.setSelected(false);
            d3.setSelected(false);
            d4.setSelected(false);
            d5.setSelected(false);

            rollCount = 0; // Zar atma sayacını sıfırla.

            // Zar atma ve skor gönderme butonlarını devre dışı bırak (oyun başlayana kadar).
            rollButton.setEnabled(false);
            sendButton.setEnabled(false);

            // Skor tablosunu temizle.
            int rowCount = scoreTableModel.getRowCount();
            int columnCount = scoreTableModel.getColumnCount();

            // Skor tablosundaki her hücreyi dolaş ve içeriğini boşalt.
            // İlk sütun (kategori isimleri) zaten boşaltılmamalıdır, bu kodda col = 0 da boşaltılmaktadır.
            // Eğer kategori isimleri ilk sütundaysa, döngü `col = 1`'den başlatılmalıdır.
            for (int row = 0; row < rowCount; row++) {
                for (int col = 0; col < columnCount; col++) { // col = 1'den başlatılabilir.
                    scoreTableModel.setValueAt("", row, col); // Hücre değerini boş string yap.
                }
            }

            System.out.println("GameGUI sıfırlandı, yeni oyun bekleniyor.");
        });
    }

    /**
     * Oyun sonu mesajlarını (oyuncuların skorları, kazanan bilgisi) toplar ve
     * gösterir. Eğer bir kazanan veya beraberlik mesajı gelirse, oyun sonu
     * özetini gösterir ve oyuncuya tekrar oynamak isteyip istemediğini sorar.
     *
     * @param message Eklenecek oyun sonu mesajı.
     */
    public void addGameOverMessage(String message) {
        if (gameOverSummary != null) {
            gameOverSummary.append(message).append("\n"); // Mesajı özete ekle.
            // Eğer gelen mesaj bir "Kazanan" veya "Oyun berabere" mesajı ise, oyunu bitir ve seçenekleri sun.
            if (message.startsWith("Kazanan:") || message.startsWith("Oyun berabere bitti!")) {
                SwingUtilities.invokeLater(() -> {
                    // Oyun bitti mesajını içeren bir JOptionPane göster.
                    JOptionPane.showMessageDialog(this, gameOverSummary.toString(), "Oyun Bitti!", JOptionPane.INFORMATION_MESSAGE);

                    disableGameControls(); // Oyun kontrollerini devre dışı bırak.

                    // Oyuncuya tekrar oynamak isteyip istemediğini sor.
                    int response = JOptionPane.showConfirmDialog(this,
                            "Tekrar oynamak ister misiniz?", "Yeni Oyun",
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                    if (response == JOptionPane.YES_OPTION) {
                        // Eğer oyuncu 'Evet' derse, sunucuya "RESTART" mesajı gönder.
                        if (connection != null) {
                            connection.sendMessage("RESTART");
                            resetGUIForNewGameRequest(); // GUI'yi yeni oyun için sıfırla.
                        }
                    } else {
                        // Eğer oyuncu 'Hayır' derse, sunucuya "QUIT" mesajı gönder ve uygulamayı kapat.
                        if (connection != null) {
                            connection.sendMessage("QUIT");
                        }
                        System.exit(0); // Uygulamayı tamamen kapat.
                    }
                });
            }
        }
    }

    /**
     * Oyun kontrollerini (butonlar, zar tutma düğmeleri, skor tablosu) devre
     * dışı bırakır. Genellikle oyun bittiğinde veya sıra başka bir oyuncudayken
     * çağrılır.
     */
    private void disableGameControls() {
        rollButton.setEnabled(false); // Zar atma butonunu devre dışı bırak.
        sendButton.setEnabled(false); // Skor gönderme butonunu devre dışı bırak.

        JToggleButton[] toggleButtons = {d1, d2, d3, d4, d5}; // Zar tutma butonları.
        for (JToggleButton tb : toggleButtons) {
            tb.setEnabled(false); // Tüm zar tutma butonlarını devre dışı bırak.
        }
        categoryTable.setEnabled(false); // Kategori tablosunu devre dışı bırak.
    }

    /**
     * "ZAR AT" butonuna tıklandığında tetiklenen olay. Oyuncunun sırası
     * değilse, 3 kezden fazla zar atmışsa veya tutulan zarlar yoksa ilgili
     * uyarıları gösterir. Ardından tutulan zarların indekslerini sunucuya
     * göndererek zar atma isteği yapar.
     *
     * @param evt Olay bilgisi.
     */
    private void rollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollButtonActionPerformed

        if (currentTurnIndex != myPlayerIndex) {
            JOptionPane.showMessageDialog(this, "Sıra sizde değil!"); // Sıra kendisinde değilse uyarı ver.
            return;
        }

        if (rollCount >= 3) {
            JOptionPane.showMessageDialog(this, "3 kez zar attınız. Artık puanınızı seçin"); // 3 atış hakkı dolduysa uyarı ver.
            rollButton.setEnabled(false); // Zar atma butonunu devre dışı bırak.
            return;
        }
        JToggleButton[] toggleButtons = {d1, d2, d3, d4, d5}; // Zar tutma butonları.
        StringBuilder heldIndices = new StringBuilder(); // Tutulan zar indekslerini toplamak için.

        // Hangi zarların tutulduğunu belirle ve sunucuya göndermek için virgülle ayrılmış bir string oluştur.
        for (int i = 0; i < 5; i++) {
            if (toggleButtons[i].isSelected()) {
                if (heldIndices.length() > 0) {
                    heldIndices.append(",");
                }
                heldIndices.append(i); // Tutulan zarın indeksini ekle.
            }
        }

        // Sunucuya "ROLL" komutu ile tutulan zar indekslerini gönder.
        // Eğer hiçbir zar tutulmadıysa sadece "ROLL" gönderilir.
        connection.sendMessage("ROLL" + (heldIndices.length() > 0 ? ":" + heldIndices.toString() : ""));

        rollCount++; // Zar atma sayacını artır.

        if (rollCount >= 3) {
            rollButton.setEnabled(false); // 3 atış yapıldıysa zar atma butonunu devre dışı bırak.
        }
    }//GEN-LAST:event_rollButtonActionPerformed
    /**
     * Skor tablosundaki bir hücreye tıklandığında tetiklenen olay. Oyuncunun
     * sırası değilse veya başka bir oyuncunun sütununa tıklanmışsa uyarı verir.
     * Seçilen hücrenin daha önce kullanılıp kullanılmadığını kontrol eder ve
     * uygunsa seçimi kaydeder.
     *
     * @param evt Olay bilgisi.
     */
    private void scoreTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoreTable1MouseClicked
        if (currentTurnIndex != myPlayerIndex) {
            JOptionPane.showMessageDialog(this, "Sıra sizde değil. Skor seçimi yapamazsınız.");
            selectedRow = -1; // Seçimi sıfırla.
            selectedColumn = -1;
            return;
        }

        int row = scoreTable1.rowAtPoint(evt.getPoint()); // Tıklanan satırın indeksini al.
        int col = scoreTable1.columnAtPoint(evt.getPoint()); // Tıklanan sütunun indeksini al.

        // Eğer tıklanan satır geçerli bir kategori satırıysa (genellikle 0. satır başlık olduğundan > 0)
        // ve sütun geçerli bir sütunsa devam et.
        if (row > 0 && col >= 0 && col < scoreTableModel.getColumnCount()) {
            // Sadece kendi skor sütununa skor girebilir.
            if (col == myPlayerIndex) {
                Object cellValue = scoreTableModel.getValueAt(row, col);
                // Eğer hücre boşsa, boş stringse veya "0" ise (yani henüz skor girilmemişse)
                if (cellValue == null || cellValue.toString().trim().isEmpty() || cellValue.toString().equals("0")) {
                    selectedRow = row; // Seçilen satır ve sütunu kaydet.
                    selectedColumn = col;

                    // Bu kısım, hücreye tıklanır tıklanmaz skoru hesaplama girişimidir.
                    // Genellikle skor hesaplaması "SKOR GÖNDER" butonuna basıldığında yapılır.
                    // Bu blokta doğrudan bir işlem yapmayabiliriz, sadece seçimi kaydetmeliyiz.
                    if (dices[0] != null) {
                        int[] diceValues = new int[5];
                        for (int i = 0; i < 5; i++) {
                            diceValues[i] = dices[i].getValue();
                        }
                        String category = categoryTable.getValueAt(selectedRow, 0).toString().toLowerCase();
                        // Burada skoru hesaplamak yerine sadece seçimi onaylayabiliriz.
                        // Skor hesaplama ve gönderme işlemi sendButtonActionPerformed'da yapılır.
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Bu kategori zaten kullanıldı. Lütfen başka bir kategori seçin.");
                    selectedRow = -1; // Seçimi sıfırla.
                    selectedColumn = -1;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Sadece kendi sütununuza skor girebilirsiniz.");
                selectedRow = -1; // Seçimi sıfırla.
                selectedColumn = -1;
            }
        } else {
            selectedRow = -1; // Geçersiz tıklama durumunda seçimi sıfırla.
            selectedColumn = -1;
        }

    }//GEN-LAST:event_scoreTable1MouseClicked

    /**
     * Skor tablosuna bir skoru ekler, eğer ilgili hücre henüz boşsa. Bu metod,
     * sunucudan gelen skor güncellemelerini yansıtmak için kullanılır.
     *
     * @param row Skorun ekleneceği satır indeksi.
     * @param col Skorun ekleneceği sütun indeksi.
     * @param score Eklenecek puan değeri.
     */
    public void addScoreIfNotUsed(int row, int col, int score) {
        Object cellValue = scoreTableModel.getValueAt(row, col);
        // Eğer hücre boşsa, boş stringse veya "0" ise (henüz skor girilmemişse) VEYA gelen skor zaten hücredeki skorla aynıysa (gereksiz güncelleme önlemek için)
        if (cellValue == null || cellValue.toString().trim().isEmpty() || cellValue.toString().equals("0") || (Integer.toString(score).equals(cellValue.toString()))) {
            scoreTableModel.setValueAt(score, row, col); // Skoru tabloya ekle.
            System.out.println("Skor tablosu güncellendi: [" + row + "," + col + "] -> " + score);
        } else {
            System.out.println("Hücre [" + row + "," + col + "] zaten dolu (" + cellValue + "), sunucudan gelen güncelleme atlandı.");
        }
    }

    /**
     * "SKOR GÖNDER" butonuna tıklandığında tetiklenen olay. Oyuncunun sırası
     * değilse, skor seçimi yapılmamışsa veya geçersiz bir kategori seçildiyse
     * uyarı verir. Zar değerlerini ve seçilen kategori bilgilerini sunucuya
     * "MOVE" komutuyla gönderir.
     *
     * @param evt Olay bilgisi.
     */
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        if (currentTurnIndex != myPlayerIndex) {
            JOptionPane.showMessageDialog(this, "Sıra sizde değil!");
            return;
        }

        // Geçerli bir skor hücresi seçilip seçilmediğini kontrol et.
        if (selectedRow == -1 || selectedColumn == -1 || selectedRow == 0) { // 0. satır genellikle kategori başlığıdır.
            JOptionPane.showMessageDialog(this, "Lütfen skorunuzu yazmak istediğiniz bir kategori seçin.");
            return;
        }

        // Sadece kendi sütununa skor gönderebilir.
        if (selectedColumn != myPlayerIndex) {
            JOptionPane.showMessageDialog(this, "Sadece kendi sütununuza skor gönderebilirsiniz.");
            selectedRow = -1; // Seçimi sıfırla.
            selectedColumn = -1;
            return;
        }

        Object cellValue = scoreTableModel.getValueAt(selectedRow, selectedColumn);
        // Seçilen kategorinin daha önce kullanılıp kullanılmadığını kontrol et.
        if (cellValue != null && !cellValue.toString().trim().isEmpty() && !cellValue.toString().equals("0")) {
            JOptionPane.showMessageDialog(this, "Bu kategori zaten kullanıldı. Lütfen başka bir kategori seçin.");
            selectedRow = -1; // Seçimi sıfırla.
            selectedColumn = -1;
            return;
        }

        // Mevcut zar değerlerini al.
        int[] diceValues = new int[5];
        for (int i = 0; i < 5; i++) {
            // Zarların atılmış olduğundan ve Dice nesnelerinin null olmadığından emin ol.
            if (dices[i] != null) {
                diceValues[i] = dices[i].getValue();
            } else {
                JOptionPane.showMessageDialog(this, "Zarlar henüz atılmadı veya bir hata oluştu.");
                return; // Zarlar olmadan skor gönderilemez.
            }
        }

        // Seçilen kategori adını al ve küçük harfe çevir.
        String category = categoryTable.getValueAt(selectedRow, 0).toString().toLowerCase();

        // Zar değerlerini sunucuya gönderilecek string formatına çevir.
        StringBuilder sb = new StringBuilder();
        for (int val : diceValues) {
            sb.append(val).append(" ");
        }

        // Sunucuya "MOVE" komutu ile kategori, zar değerleri, seçilen satır ve sütun bilgilerini gönder.
        // Sunucu bu bilgileri alıp skoru hesaplayacak, geçerliliğini kontrol edecek ve tabloyu güncelleyecek.
        if (connection != null) {
            // Mesaj formatı: MOVE:kategori:zar1 zar2 zar3 zar4 zar5:satirIndeksi:sutunIndeksi
            connection.sendMessage("MOVE:" + category + ":" + sb.toString().trim() + ":" + selectedRow + ":" + selectedColumn);
        }

        // Hamle gönderildikten sonra zar atma ve skor gönderme butonlarını devre dışı bırak.
        // Sıra değiştiğinde `updateTurn` metodu bu butonları yeniden yönetecek.
        rollButton.setEnabled(false);
        sendButton.setEnabled(false);

        // Seçili skor hücresini sıfırla.
        selectedRow = -1;
        selectedColumn = -1;


    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * Birinci zar tutma (toggle) butonuna tıklandığında tetiklenen olay. Zar
     * tutulmuşsa ilgili zar görselini devre dışı bırakır, aksi takdirde
     * etkinleştirir.
     *
     * @param evt Olay bilgisi.
     */

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        if (d1.isSelected()) {
            dice1.setEnabled(false); // Zar tutulduysa görseli devre dışı bırak.
        } else {
            dice1.setEnabled(true); // Zar serbest bırakıldıysa görseli etkinleştir.
        }
    }//GEN-LAST:event_d1ActionPerformed

    /**
     * İkinci zar tutma (toggle) butonuna tıklandığında tetiklenen olay. Zar
     * tutulmuşsa ilgili zar görselini devre dışı bırakır, aksi takdirde
     * etkinleştirir.
     *
     * @param evt Olay bilgisi.
     */
    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        if (d2.isSelected()) {
            dice2.setEnabled(false);
        } else {
            dice2.setEnabled(true);
        }
    }//GEN-LAST:event_d2ActionPerformed
    /**
     * Üçüncü zar tutma (toggle) butonuna tıklandığında tetiklenen olay. Zar
     * tutulmuşsa ilgili zar görselini devre dışı bırakır, aksi takdirde
     * etkinleştirir.
     *
     * @param evt Olay bilgisi.
     */
    private void d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3ActionPerformed
        if (d3.isSelected()) {
            dice3.setEnabled(false);
        } else {
            dice3.setEnabled(true);
        }
    }//GEN-LAST:event_d3ActionPerformed
    /**
     * Dördüncü zar tutma (toggle) butonuna tıklandığında tetiklenen olay. Zar
     * tutulmuşsa ilgili zar görselini devre dışı bırakır, aksi takdirde
     * etkinleştirir.
     *
     * @param evt Olay bilgisi.
     */
    private void d4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4ActionPerformed
        if (d4.isSelected()) {
            dice4.setEnabled(false);
        } else {
            dice4.setEnabled(true);
        }
    }//GEN-LAST:event_d4ActionPerformed
    /**
     * Beşinci zar tutma (toggle) butonuna tıklandığında tetiklenen olay. Zar
     * tutulmuşsa ilgili zar görselini devre dışı bırakır, aksi takdirde
     * etkinleştirir.
     *
     * @param evt Olay bilgisi.
     */
    private void d5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d5ActionPerformed
        if (d5.isSelected()) {
            dice5.setEnabled(false);
        } else {
            dice5.setEnabled(true);
        }
    }//GEN-LAST:event_d5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable categoryTable;
    private javax.swing.JToggleButton d1;
    private javax.swing.JToggleButton d2;
    private javax.swing.JToggleButton d3;
    private javax.swing.JToggleButton d4;
    private javax.swing.JToggleButton d5;
    private javax.swing.JLabel dice1;
    private javax.swing.JLabel dice2;
    private javax.swing.JLabel dice3;
    private javax.swing.JLabel dice4;
    private javax.swing.JLabel dice5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JButton rollButton;
    private javax.swing.JTable scoreTable1;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
